name: Test Helpers
on:
  workflow_run:
    workflows: ["Pull Request Tests"]
    types:
      - requested
env:
  app: "Accept:application/vnd.github.v3+json"

jobs:
  postcomment:
    name: Post repocheck comments
    runs-on: ubuntu-20.04

    steps:
    - name: Check out codes
      uses: actions/checkout@v2

    - name: Wait until repocheck is complete
      env:
        AUTH: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd $GITHUB_WORKSPACE/tests/ci
        conclusion=$(echo ${{ github.event.workflow_run.jobs_url }} | ./build_status_check.py "Check if repos are up to date")
        echo $conclusion

    - name: Retrieve repocheck comment
      uses: actions/cache@v2
      with:
        path: comment_file
        key: comment-${{ github.env.workflow_run.id }}

    - name: Notify the PR author
      run: |
        comment=$(cat comment_file)
        url=$GITHUB_API_URL/repos/$GITHUB_REPOSITORY
        echo "url is $url"
        head_sha=${{ github.event.workflow_run.head_sha }}
        echo "head_sha is $head_sha"
        cd $GITHUB_WORKSPACE/tests/ci
        pr_number=$(curl -sS -H "$app" $url/pulls | ./json_helper.py get_pr $head_sha)
        if [[ -n $comment && -n $pr_number ]]; then
          curl -sS -X POST -H "$app" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $url/issues/$pr_number/comments -d '{"body": "'"${comment}"'"}'
        fi

#  startrunner:
#    name: Start ec2 instances
#    runs-on: ubuntu-20.04
#
#    steps:
#    - name:
#      run:
#
#  stoprunner:
#    name: Stop ec2 instances
#    runs-on: ubuntu-20.04
#    needs: startrunner
#
#    steps:
#    - name:
#      run:
