name: Pull Request Tests

on:
  push:
    branches:
    - feature/ContInteg-tests
  pull_request:
    branches:
    - feature/ContInteg-tests

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest

    outputs:
      tn: ${{ steps.parse.outputs.tn }}
      bld: ${{ steps.parse.outputs.bld }}
      test: ${{ steps.parse.outputs.test }}

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Parse cases
      id: parse
      run: |
        var1=$(sed -n 1p ${GITHUB_WORKSPACE}/tests/ci.test)
        var2=$(sed -n 2p ${GITHUB_WORKSPACE}/tests/ci.test)
        var3=''
        [[ $var2 =~ thr || $var2 =~ mpi || $var2 =~ dcp || $var2 =~ rst ]] && var3+='std'
        [[ $var2 =~ bit ]] && var3+=' bit'
        [[ $var2 =~ dbg ]] && var3+=' dbg'
        var3=$(echo $var3 | sed -e 's/^ *//' -e 's/ *$//')
        var4='{"bld_set":['
        for i in $var3; do var4+="\"$i\","; done
        var4=$(echo $var4 | sed -e 's/,$//')
        var4+=']}'

        tv=()
        var5='{"test_set":['
        for i in $var2; do
          var5+="\"$i\","
          [[ $i =~ thr || $i =~ mpi || $i =~ dcp || $i =~ rst ]] && tv+=( std )
          [[ $i =~ bit ]] && tv+=( bit )
          [[ $i =~ dbg ]] && tv+=( dbg )
        done

        var5=$(echo $var5 | sed -e 's/,$//')
        var5+='],"include":['
        j=0
        for i in $var2; do var5+="{\"test_set\":\"$i\",\"artifact\":\"${tv[$j]}\"},"; j=$((j+1)); done
        var5=$(echo $var5 | sed -e 's/,$//')
        var5+=']}'

        echo "::set-output name=tn::$var1"
        echo "::set-output name=bld::$var4"
        echo "::set-output name=test::$var5"

        echo $var1
        echo $var4
        echo $var5

  build:
    name: Build ${{ matrix.bld_set }}
    needs: setup
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.bld) }}

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: |
        printf '{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json >/dev/null
        sudo systemctl restart docker
        sleep 10
        cd tests && ./ci.sh -n ${{ needs.setup.outputs.tn }} -b ${{ matrix.bld_set }}

    - name: Free up disk space
      run: |
        sudo docker rmi $(sudo docker image ls | grep -E -m1 '<none>' | awk '{ print $3 }')
        sudo docker rmi $(sudo docker image ls | awk '/ci-test-base/ { print $3 }')

    - name: Prepare artifacts
      run: |
        cd tests
        sudo docker save ci-test-weather | gzip >ci-test-weather.tar.gz
        tar cvjf artifact.tar.bz2 ci-test-weather.tar.gz ci.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.bld_set }}.artifact.tar.bz2
        path: tests/artifact.tar.bz2

  utest:
    name: Unit test (${{ needs.setup.outputs.tn }}, ${{ matrix.test_set }})
    needs: [setup,build]
    runs-on: ubuntu-latest
    #runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup.outputs.test) }}

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: ${{ matrix.artifact }}.artifact.tar.bz2

    - name: Prepare artifacts
      run: |
        pwd
        ls -l
        tar xvjf artifact.tar.bz2 && rm -f artifact.tar.bz2
        sudo docker load --input ci-test-weather.tar.gz && rm -f ci-test-weather.tar.gz

    - name: Run utest
      run: ./ci.sh -n ${{ needs.setup.outputs.tn }} -r ${{ matrix.test_set }}

    - name: Upload memory usage file
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: memory_stat_${{ matrix.test_set }}
        path: memory_stat

    #- name: Clean up
